[project]
name = "pyMHF"
description = "python Modding and Hooking Framework"
requires-python = ">=3.9"
license = {file = "LICENSE.md"}
keywords = ["hooking", "games", "hacking", "modding"]
authors = [
  {name = "monkeyman192"}
]
maintainers = [
  {name = "monkeyman192"}
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Environment :: Win32 (MS Windows)",
  "License :: OSI Approved :: MIT License",
  "Operating System :: Microsoft",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
  "cyminhook>=0.1.4",
  "psutil~=5.9.5",
  "pymem[speed]~=1.12.0",
  "keyboard",
  "semver",
  "pywin32",
  "dearpygui~=1.11.0",
  "questionary",
  "pywinctl",
]
version = "0.1.7+dev2"

[tool.setuptools.package-dir]
pymhf = "pymhf"

[project.urls]
Homepage = "https://github.com/monkeyman192/pyMHF"
Repository = "https://github.com/monkeyman192/pyMHF"

[project.scripts]
pymhf = "pymhf:run"

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"
