name: pyMHF

on:
  # Run on all branches except for the gh-pages branch
  push:
    paths-ignore:
      - '*.md'
    branches-ignore:
      - 'gh-pages'
  pull_request:
    paths-ignore:
      - '*.md'
    branches-ignore:
      - 'gh-pages'
  create:

jobs:
  build_test:
    name: Build artefacts
    runs-on: Windows-latest
    strategy:
      fail-fast: false
      matrix:
        py_ver: [{version: '3.9'}] # , {version: '3.10'}, {version: '3.11'}]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.py_ver.version}}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.py_ver.version}}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip uv
          uv sync --frozen --dev
      - name: Build Python ${{ matrix.py_ver.version}} wheel
        run: uv build
      - name: Lint and format code
        run: |
          uv run ruff check ./pymhf
          uv run ruff format --check ./pymhf
      - name: Upload Wheels
        uses: actions/upload-artifact@v4
        with:
          name: pyMHF
          path: dist/*
  release:
    name: Release pyMHF wheels and source build
    # Only run this job if the commit was tagged.
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: windows-latest
    needs: [build_test]
    steps:
      - name: Download files for release
        uses: actions/download-artifact@v4
      - name: See what files we have
        run: ls
        shell: bash
      # TODO: Add release action
